nelmio_cors:
    paths:
        '^':
            allow_origin: ['*']  # Use '*' for public APIs, or specify your Angular app URL
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            max_age: 3600
            expose_headers: []
